---
- hosts: all
  become: true
  tasks:

  - name: Download Zabbix repository
    ansible.builtin.get_url:
      url: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.4+ubuntu24.04_all.deb
      dest: .

  - name: Install Zabbix repository
    ansible.builtin.apt:
      deb: zabbix-release_latest_7.4+ubuntu24.04_all.deb

  - name: Update repoository
    ansible.builtin.apt:
      update_cache: yes

  - name: Install zabbix-server-pgsql
    ansible.builtin.apt:
      name: zabbix-server-pgsql

  - name: Install zabbix-frontend-php
    ansible.builtin.apt:
      name: zabbix-frontend-php

  - name: Install php8.3-pgsql
    ansible.builtin.apt:
      name: php8.3-pgsql

  - name: Install zabbix-nginx-conf
    ansible.builtin.apt:
      name: zabbix-nginx-conf

  - name: Install zabbix-sql-scripts
    ansible.builtin.apt:
      name: zabbix-sql-scripts

  - name: Install zabbix-agent2
    ansible.builtin.apt:
      name: zabbix-agent2

  - name: Install zabbix-agent2-plugin-mongodb
    ansible.builtin.apt:
      name: zabbix-agent2-plugin-mongodb

  - name: Install zabbix-agent2-plugin-mssql
    ansible.builtin.apt:
      name: zabbix-agent2-plugin-mssql

  - name: Install zabbix-agent2-plugin-postgresql
    ansible.builtin.apt:
      name: zabbix-agent2-plugin-postgresql

